stages:
  train:
    cmd: python src/train.py
    deps:
      - data/winequality-red.csv
      - data/winequality-white.csv
      - src/train.py
    outs:
      - models/model.pkl
    metrics:
      - metrics.json